- name: installing using loops
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'gcc', state: 'absent' }
    - { name: 'git', state: 'present' }
    - { name: 'sql', state: 'present' }
    - { name: 'zip', state: 'absent' }
